### ISSUE TITLE
Update Request for resend dependency

### ISSUE THREAD

**Issue by llnnse** [pevey/medusa-plugin-resend#1]
Hey,
I've been setting up your resend plugin locally and am encountering an error described [here](https://github.com/resendlabs/resend-node/issues/147#issue-1826464062). Since I'm getting the same ECONNREFUSED error, I can't really send emails.

Thank you for your work!

**Comment by pevey** [comment]
From that thread, it looks like it can be resolved by force updating the underlying resend-node dependency.  I'll officially update it in the next release.

**Comment by pevey** [comment]
This issue should now be resolved with plugin version 1.1.0, which uses the resend sdk package version 1.0.0.
